---
title: "Compasiron between RF and XGB"
author: "Samara"
date: "2025-10-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
# Define business costs
cost_per_fn <- 5000  # Default loss (bad customer approved)
cost_per_fp <- 500   # Lost profit (good customer rejected)

# Random Forest costs
rf_cost <- (40 * cost_per_fn) + (12 * cost_per_fp)
cat("Random Forest Total Cost: €", rf_cost, "\n")


# XGBoost costs
xgb_cost <- (35 * cost_per_fn) + (13 * cost_per_fp)
cat("XGBoost Total Cost: €", xgb_cost, "\n")


# Difference
cat("Cost Difference: €", rf_cost - xgb_cost, "\n")


```

XGB cost is lower. That means, XGB model perform better.



```{r}
# But Random Forest approves more customers = more revenue
rf_approvals <- 128 + 40  # 168 total
xgb_approvals <- 127 + 35  # 162 total
additional_approvals <- rf_approvals - xgb_approvals  

# If each good approval generates €2,000 profit
revenue_per_approval <- 2000
additional_revenue <- 6 * revenue_per_approval  
cat("Additional Revenue (RF): €", additional_revenue, "\n")


# Net impact
net_difference <- additional_revenue - (rf_cost - xgb_cost)
cat("Net Financial Impact on higer loan approvals: €", net_difference, "\n")

```
Eventhough RF approves more loan and if we assume it generates more revenue, still RF cannot outperform XGB. Therefore XGB model perform better financially.
